# Generated by Django 2.2.6 on 2019-12-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='saldo',
        ),
    ]
